[package]
name = "lesson1"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "hw1"
path = "src/hw1.rs"
[[bin]]
name = "hw2"
path = "src/hw2.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
